<?php
return ['project-id-version'=>'WooCommerce B2B Invoice','report-msgid-bugs-to'=>'','pot-creation-date'=>'2025-03-30 10:25+0000','po-revision-date'=>'2025-03-30 10:37+0000','last-translator'=>'Admin','language-team'=>'Finnish','language'=>'fi','plural-forms'=>'nplurals=2; plural=n != 1;','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-loco-version'=>'2.7.1; wp-6.7.2','x-domain'=>'woocommerce-b2b-invoice','messages'=>['Add'=>'Lisää','Adds a custom WooCommerce payment gateway for B2B customers, allowing invoice-based payments with advanced restrictions and user-specific settings.'=>'Lisää WooCommerceen mukautetun maksutavan yritysasiakkaille, mahdollistaen laskulla maksamisen kehittyneillä rajoituksilla ja käyttäjäkohtaisilla asetuksilla.','Allow pay by invoice'=>'Salli maksaminen laskulla','Allowed Shipping Methods'=>'Sallitut toimitustavat','Bill to company'=>'Lasku yritykselle','Business ID'=>'Y-tunnus','Choose shipping methods allowed when using this gateway.'=>'Valitse sallitut toimitustavat, kun käytät tätä yhdyskäytävää.','Choose the order status to apply when an invoice is used.'=>'Valitse tilauksen tila, joka asetetaan maksun jälkeen.','Companies'=>'Yritykset','Company'=>'Yritys','Company name'=>'Yrityksen nimi','Default Order Status'=>'Tilauksen oletustila','Delete'=>'Poista','Description'=>'Kuvaus','E-invoice address'=>'Verkkolaskuosoite','Enable Invoice Payment'=>'Ota laskumaksu käyttöön','Enable/Disable'=>'Ota käyttöön / Poista käytöstä','Intermediary'=>'Välittäjä','Invoice payment has been temporarily disabled on your account. Please contact customer service.'=>'Laskulla maksaminen on tilapäisesti poistettu käytöstä tililtäsi. Ota yhteyttä asiakaspalveluun.








','Invoice reference'=>'Laskun viite','Invoice settings'=>'Laskuasetukset','No billing companies were found in your account, please contact customer service.'=>'Tililtäsi ei löytynyt laskutusyrityksiä. Otathan yhteyttä asiakaspalveluun.

','Pay easily by e-invoice. The invoice will be sent to your billing address'=>'Maksa vaivattomasti verkkolaskulla – lasku toimitetaan laskutusosoitteeseesi.','Payment by invoice is not allowed on your account.'=>'Tililläsi ei ole oikeutta maksaa laskulla.','Reference'=>'Viite','Riko Valkonen'=>'Riko Valkonen','Select company'=>'Valitse yritys','Temporarily disable invoice payment'=>'Poista laskulla maksaminen tilapäisesti käytöstä','This controls the description which the user sees during checkout.'=>'Tämä teksti näkyy käyttäjälle maksutavan valinnan yhteydessä kassalla.','This controls the title which the user sees during checkout.'=>'Tämä otsikko näytetään käyttäjälle kassalla maksutapaa valittaessa.','Title'=>'Otsikko','WooCommerce B2B Invoice'=>'WooCommerce B2B Lasku','You are currently unable to use bill pay. Please contact customer service.'=>'Laskulla maksaminen ei ole tällä hetkellä käytettävissä. Ole hyvä ja ota yhteyttä asiakaspalveluun.']];
